name: CI

on:
  pull_request:
    branches:
      - master
      - dev
      - dev-*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack success
      if: success()
      id: slack # IMPORTANT: reference this step ID value in future Slack steps
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.1
      with:
        channel: github-actions
        status: STARTING
        color: warning

    - name: Set up Python
    - uses: actions/checkout@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        python-version: '3.x'
      run: |
        py.test --cov-report=xml --cov=securenative tests/

    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: github-actions
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: github-actions
        status: FAILED
        color: danger
